# Generated by Django 5.1.4 on 2026-03-06 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('current_aqi', models.FloatField()),
                ('forecast_24h', models.FloatField()),
                ('forecast_7d', models.FloatField()),
                ('forecast_30d', models.FloatField()),
                ('category_24h', models.CharField(max_length=20)),
                ('category_7d', models.CharField(max_length=20)),
                ('category_30d', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AQIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('co', models.FloatField()),
                ('so2', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('predicted_category', models.CharField(blank=True, choices=[('Good', 'Good'), ('Moderate', 'Moderate'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor'), ('Severe', 'Severe')], max_length=20)),
                ('aqi_value', models.IntegerField(default=0)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('iot', 'IoT Sensor'), ('api', 'API')], default='manual', max_length=10)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aqi_app.station')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
